name: GPB IT Factory Backend 2024 CI
on:
  pull_request:
    branches: [ "trunk" ]
    types: [opened]

jobs:
  assign_random_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Team Members
        id: fetch_team_members
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const teamName = 'team';
            const { data: team } = await github.teams.getByName({ org: 'gpb-it-factory', team_slug: teamName });
            const { data: members } = await github.teams.listMembers({ team_id: team.id, role: 'member' });
            const randomMember = members[Math.floor(Math.random() * members.length)];
            console.log(randomMember.login);
            console.log(randomMember);
            return { randomMemberLogin: randomMember.login };

      - name: Assign Random Reviewer
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: ${{ steps.fetch_team_members.outputs.randomMemberLogin }}
